theme: jekyll-theme-minimal
title: "Generating Synthetic Labeled Data from Anatomical Models"
description: Using anatomical models as high quality ground truth annotations, we propose a pipeline to generate large synthetic
  datasets for training convolutional neural networks.
logo: /docs/assets/img/intro.png