title: "Generating Synthetic Labeled Data from Anatomical Models"
logo: /assets/img/intro.png
description: Using anatomical models as high quality ground truth annotations, we propose a pipeline to generate large synthetic
  datasets for training convolutional neural networks.
theme: jekyll-theme-minimal
google_analytics: UA-184903649-1
